### ISSUE TITLE
/cloudfoundryendpoint fails when using new routes

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Management#10]
Hi,
I have unique problem I guess. When I push my app, I get an route https://<<app_name>>.<<domain_name>. At this point the PCF dash board is able to hit the /cloudfoundryapplication/info or /cloudfoundryapplication/health end points etc:-. 

As per our enterprise mandate, we need to have standard for the route as per which we have a generic host name for a group of application and then the path. Now if I delete the route created by the push and provide the https://<<host_name>>/<<path_to_application>> suddenly the /cloudfoundryapplication starts to fail. It starts giving 404 as a result we are not able to get the health dash board and other dashboard.

How do I work around this problem ? Is it mandatory for me to have two routes to each of my micro services

**Comment by dwilliss** [comment]
I just ran into this same issue and found this while researching.  
I tried creating 2 routes for each microservice too and that didn't work.   It gets some error about not being able to have conflicting "/" and "/some_route".

**Comment by VenkateshSrini** [comment]
@dwilliss ,
Is this a .NET or .NET core application. If it is a .NET application you will have the problem as the hwc build packs does not allow multiple routes. On the other had if it is a .NET core application that will allow multiple routes. Can you please share the code so that I can have a look on this. 

Meanwhile creating multiple routes is not the solution. There should be a better way to do this?

Thanks and regards
Venkatesh

**Comment by alfusinigoj** [comment]
@VenkateshShrini, I did a test to replicate in a .Net core application and it turned out to be working fine for applications using context routing. For e.g if your application’s context path is ‘application1’, your application setting for management should be as below.

management:endpoints:path = /application1/cloudfoundryapplication

Can you please give a try and confirm this?

We may still need to figure out @dwillis issue for a .Net app using hwc buildpack

**Comment by VenkateshSrini** [comment]
@alfusinigoj ,
I tried this solution. It does not work. In fact what is happening is the steeltoe logo against the app itself is not appearing. Could you please share your code of sample app ? May  be we will see if we are missing something

**Comment by alfusinigoj** [comment]
@venkateshsrini

Here is the application code. https://github.com/alfusinigoj/dotnet_core_webapi/tree/master/src/Dotnet.Core.Web.Api

**Comment by alfusinigoj** [comment]
@VenkateshSrini ,

Can you check if you have added the middleware.. ```app.UsePathBase("/sample2");```

**Comment by dwilliss** [comment]
My case is a legacy ASHX, not .NET Core, so it's on the hwc buildpack.  We're using the Steeltoe.Management.EndpointWeb.  
Here's another bit of information:  There are multiple apps.  The one that's at / (with no path in the route) is .NET Core on a binary build pack.  The app that has a path in the route is the older ASHX style so it's an hwc build pack.  
I also tested pushing an 2nd copy of the .NET Core app so it has a path and that works.  So I'm leaning towards this being an issue where the hwc build pack just doesn't understand it.

**Comment by VenkateshSrini** [comment]
@alfusinigoj ,
That is a good point. I did not do that. Since I'm held up with high priority task and will try that let you know.

**Comment by VenkateshSrini** [comment]
@alfusinigoj ,
The addition of UsePathBase worked. However if we have mention app name of the route then we should remove the app name from the route. That is the only change that we need to do.

**Comment by VenkateshSrini** [comment]
@dwilliss ,
I will try to shoot a few blind arrows with the info you gave to us
1) I think but not sure, we can host ASHX also with HWC. Please see the HWC go config at https://github.com/cloudfoundry/hwc/blob/master/hwcconfig/application_host_config.go. I think this is what is used by hwc build pack also. In this you can see the ASHX middleware is added. So there should be no issued
2) Why should the .NET core app be in the route? Cant you not host it separately using HWC buildpack. If you want this app to hit before hitting your .NET apps then cant you not add this as Route Service. We had one such requirement to do URL re-direction based on region and this is how we achieved it. The documentation for that is at https://docs.cloudfoundry.org/services/route-services.html

**Comment by dwilliss** [comment]
To answer your questions:
1. Yes, the ashx is being hosted with hwc.
2. It's complicated, but for backwards compatibility when running not under Cloud Foundry, the main app (which is .NET Core) is configured to look for auxiliary apps with a URL relative to itself on the same host name.  This is because in the non-cloud scenario, they're all running on the same IIS.  We have the possibility to configure it so that the auxiliary apps are absolute URLs that could point to a different host, but for reasons that are difficult to explain, we can't actually use that.

**Comment by dtillman** [comment]
@VenkateshSrini :  Is your issue resolved?
Dave

**Comment by dwilliss** [comment]
Mine seems to be solved by substituting a newer StackExchange.Redis package.  That worked for the memory issue, anyway.  We weren't able to keep that because the Microsoft DLL for handling session state via redis has a hard dependency on the older one, so everything _except_ the health checks failed.

As long as the /cloudfoundryappliation/heath endpoint is only used occasionally via the CF Apps Manager, the memory leak is barely noticable.  It's only when it gets called every 30 seconds to test the application health that it starts to add up and become a problem.

We decided to completely disable that for now anyway because the every-30-seconds check has an unreasonably short timeout (1 second), and the health contributor for config server sometimes takes longer than that, causing it to "crash" our applications.

**Comment by VenkateshSrini** [comment]
@dtillman ,
Thanks for sharing soln. to the new issue had unearthed. But if I may ask, the earlier problem of route still open. How you were able to get the /cloudfoundryapplication work with application that has .NET Core and .NET all coupled together.

**Comment by dtillman** [comment]
@VenkateshSrini 

Sorry , I'm not understanding your question.
"How you were able to get the /cloudfoundryapplication work with application that has .NET Core and .NET all coupled together."
Dave

**Comment by VenkateshSrini** [comment]
@dtillman ,
When we add the management endpoints. PCF periodically hits the service to check the health and other status. If we have enabled all the health management then it hits the aggregated management end point which is /cloudfoundry. In .NET core we add the .UseBasePath("/") and got it working.

Since you were trying a similar thing in .NET, as @alfusinigoj also told, we have not yet experimented it with .NET. So we are curious how you git the management end points working in .NET

**Comment by dwilliss** [comment]
I had some time so I came back to this.  What seems to be the problem in my case is that if my app has a path component to its route, the Apps Manager is always making the call to /path/cloudfoundryapplication.
I need it to make the call to /path/application.ashx/cloudfoundryapplication.  
I've set the management:endpoints:path to that in the environment, but Apps Manager seems to ignore that.

**Comment by alfusinigoj** [comment]
URL rewrite would be one of the options. But I haven’t tried that yet

Regards,
Alfus (+1 860 597 9273)

**Comment by dwilliss** [comment]
SUCCESS!!!!  
Maybe I missed this in the documentation or maybe it just wasn't there.
In the manifest.yml, set the environment management:endpoints:path to /WhateverYourPathIs/cloudfoundryapplication

I was trying to have /WhateverYourPathIs/AppName.ashx/cloudfoundryapplication

**Comment by alfusinigoj** [comment]
👍 Nice that you figured that out. I hope it could be a misunderstanding or miscommunication.

Regards,
Alfus (+1 860 597 9273)

**Comment by TimHess** [comment]
Looks like all problems here were resolved, closing the issue
