### ISSUE TITLE
EndpointWeb UseCloudFoundryActuators gets null reference exception

### ISSUE THREAD

**Issue by dwilliss** [SteeltoeOSS/Management#11]
I'm trying to use EndpointWeb in a legacy (non-MVC) application.
The UseCloudFoundryActuators function calls all the other UseWhateverActuator functions, passing null for the ISecurityService.  If you then try to hit the /cloudfoundryapp endpoint, it gives you a login popup.  If you try to have your healthcheck set a http check at /cloudfoundryapp/health, it fails to start the app at all because it never passes the health check.

If you call the individual UseWhateverActuators, ignoring the UseCloudFoundrySecurity, then the program blows up with a null reference error:   Partial stack trace:
```
Steeltoe.Management.Endpoint.Handler.<IsAccessAllowed>d__5.MoveNext() +122
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60 
```
If I call the individual UseWhateverActuator functions myself and pass an instance of this class, it works but of course it's not very secure.  (yes, it's VB. _Really_ legacy app)

```
    Private Class NullSecurity Implements ISecurityService

        Public Function IsAccessAllowed(context As HttpContext, target As IEndpointOptions) As Task(Of Boolean) Implements ISecurityService.IsAccessAllowed
            Return Task.FromResult(Of Boolean)(True)
        End Function
    End Class
```
Is this expected behavior, or is there an implementation of ISecurityService that I should pass instead?  I traced out the headers that get passed in and it looks like there's a barer token on the first request. I didn't check for cookies, but presumably App Manager has some way of authenticating.

**Comment by dtillman** [comment]
@dwilliss :

You should be able to pick and choose Use*() methods as needed from this [code](https://github.com/SteeltoeOSS/Management/blob/dev/src/Steeltoe.Management.EndpointWeb/ActuatorConfigurator.cs#L54).

If you are running on PCF and you want the PCF Apps Manager to expose the endpoints then you will need to use the SecurityService we provide.

Otherwise, if you want to supply your own security impl pass it in to [UseCloudFoundrySecurity](https://github.com/SteeltoeOSS/Management/blob/dev/src/Steeltoe.Management.EndpointWeb/ActuatorConfigurator.cs#L81). 


Here is a 4.x [samples](https://github.com/SteeltoeOSS/Samples/tree/dev/Management/src/AspDotNet4/CloudFoundryWeb)

Dave

**Comment by dwilliss** [comment]
If I call UseCloudFoundrySecurity and don't specify my own security implementation, then when the PCF Apps Manager calls the /cloudfoundryapplication endpoint, it gets a 503 error.

I decided to try passing null for the security to use your implementation, but also pass in a logFactory with trace logging enabled to maybe see what it was doing.  This worked for the CF Apps Manager - it shows the additional tabs and the health shows the dropdown that gives you health details for each service.

However... That was with the program's health endpoint set to my own endpoint which does basically the same as yours but we wrote it before we knew about EndpointWeb.  If I change the health endpoint to point to /cloudfoundryapplication/health, the program never passes the health check and never starts.

**Comment by dtillman** [comment]
OK... I must say I'm confused.... 

Yes, if you pass in null for the ISecurityService, then we will default and and use our default security provider which is compatible with the PCF Apps Manager.  Our security provider expects a OAuth Token to be present in the health request and is used to determine permissions.

I'm not sure I understand the "However ...." part of your response... can you elaborate?

Thanks
Dave

**Comment by dwilliss** [comment]
The PCF Apps Manager will call into the /cloudfoundryapplication/health to show the health status and that works just fine - if I set get it past the startup.

Health check for initial startup (and every 30 seconds thereafter) uses whatever URL you specify in the health-check-http-endpoint in the manifest.yml.  

If I set health-check-type to process, the app starts just fine, but of course then Cloud Foundry isn't actually monitoring the health.

If I set health-check-type to http and point the endpoint at /cloudfoundryappliation/health, the application never starts, stating that it never became healthy.   If I substitute a nerfed security provider that always returns true, it starts just fine.

It's like the CF Apps Manager understands the OAuth Token, but whatever "cf push" does to wait for the app to become healthy doesn't.

**Comment by dtillman** [comment]
Ahh... yes.. now I get it... the /cloudfoundryapplication/health actuator endpoint was not designed to be hit by the Cloud Foundry health checker.   

The CF health checker is a very basic health check and essentially checks to see if the app responds with a 200.   It doesn't understand or interpret any response data ... just looks for a 200.   It also does not send in any authenticated identity (i.e. OAuth Token) when it hits the endpoint that you configure in your manifest.yml.  The health checker is just a process running someplace that periodically hits whatever endpoint you configure and if it doesn't get a 200 response... it assumes the app is in a bad state and restarts it.  The endpoint it hits can't be secured and is wide open to anyone to hit... including PCF health checker.

The .NET and Java health actuator endpoints return a json payload with specific information about the health of the app.  The thinking is that information should be protected so that only those who should be able to see that info indeed can.  So by default , the Steeltoe security provider that is injected into the pipeline looks for a OAuth token and uses it to determine the permissions of the caller.  Depending on the result, the health is determined and the details are returned or not.

As you have discovered, you can replace the default security provider and implement whatever you'd like.

Dave

**Comment by dtillman** [comment]
I'm going to close this for now, open up a new issue if there is more to do on this!
