### ISSUE TITLE
Zipkin JSON properties should be absent instead of null

### ISSUE THREAD

**Issue by frankdirosaiv** [SteeltoeOSS/Management#34]
According to Zipkins Swagger [documentation](https://zipkin.io/zipkin-api/), a span containing a local endpoint should have IPv4 or IPv6 present or "absent if unknown". However, the request sent out by Steeltoe.Management.ExporterBase/Tracing/Zipkin/ZipkinEndpoint.cs sets this value to null. This creates a BadRequest with some Zipkin and Jaeger servers if a user is trying to Export Traces.

**Comment by jkonicki** [comment]
Duplicate to https://github.com/SteeltoeOSS/Samples/issues/58 ?

**Comment by dtillman** [comment]
@frankdirosaiv : Thanks for the problem report...

With Steeltoe 2.2 we have deprecated our implementation of OpenCensus and are now using the packages generated by the [OpenCensus ](https://github.com/census-instrumentation/opencensus-csharp)project.  We donated our code to the project some time ago and they are now creating [Nugets](https://www.nuget.org/packages?q=OpenCensus) which we depend on.

In looking at their code, the problem you're reporting still exists in their codebase ... could you please open up an issue in their repo so that this gets addressed!

Thanks again!
Dave
